package com.sportmanagement.manager.ui.theme

import androidx.compose.ui.graphics.Color

// ─── Light Scheme ─────────────────────────────────────────────────────────────
val primaryLight = Color(0xFF0D407A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD4E3FF)
val onPrimaryContainerLight = Color(0xFF224876)
val secondaryLight = Color(0xFF4E6073)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCFE2F9)
val onSecondaryContainerLight = Color(0xFF394C5E)
val tertiaryLight = Color(0xFF844C72)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD8EE)
val onTertiaryContainerLight = Color(0xFF693459)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF191C20)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF1A1B21)
val surfaceVariantLight = Color(0xFFE0E2EC)
val onSurfaceVariantLight = Color(0xFF43474E)
val outlineLight = Color(0xFF74777F)
val outlineVariantLight = Color(0xFFC3C6CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFA6C8FF)
val surfaceDimLight = Color(0xFFDAD9E0)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3FA)
val surfaceContainerLight = Color(0xFFEEEDF4)
val surfaceContainerHighLight = Color(0xFFE8E7EF)
val surfaceContainerHighestLight = Color(0xFFE2E2E9)

// ─── Dark Scheme ──────────────────────────────────────────────────────────────
val primaryDark = Color(0xFFA6C8FF)
val onPrimaryDark = Color(0xFF01315E)
val primaryContainerDark = Color(0xFF224876)
val onPrimaryContainerDark = Color(0xFFD4E3FF)
val secondaryDark = Color(0xFFB3C8DD)
val onSecondaryDark = Color(0xFF1F3344)
val secondaryContainerDark = Color(0xFF364A5B)
val onSecondaryContainerDark = Color(0xFFCFE2F9)
val tertiaryDark = Color(0xFFF7B1DD)
val onTertiaryDark = Color(0xFF4F1E42)
val tertiaryContainerDark = Color(0xFF693459)
val onTertiaryContainerDark = Color(0xFFFFD8EE)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE1E2E9)
val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF43474E)
val onSurfaceVariantDark = Color(0xFFC3C6CF)
val outlineDark = Color(0xFF8D9199)
val outlineVariantDark = Color(0xFF43474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2F3036)
val inversePrimaryDark = Color(0xFF3C6090)
val surfaceDimDark = Color(0xFF121318)
val surfaceBrightDark = Color(0xFF38393F)
val surfaceContainerLowestDark = Color(0xFF0D0E13)
val surfaceContainerLowDark = Color(0xFF1A1B21)
val surfaceContainerDark = Color(0xFF1E1F25)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33343A)

// ─── Semantic / named aliases ─────────────────────────────────────────────────
val Amber = Color(0xFFF59E0B)
val AmberContainer = Color(0xFFFFF3D9)
val AmberText = Color(0xFF92400E)

// backward-compat alias used in DashboardScreen
val SurfaceContainerLow = surfaceContainerLowLight
